name: sleuth
channels:
    - conda-forge
dependencies:
    - python==3.10.11
    - pip
    - numpy==1.24.3
    - numba==0.57.0
    - gdal==3.4.3
    - earthengine-api
    - pip:
        - "git+https://github.com/RodolfoFigueroa/URSA.git"
